baseURL = "https://yentran.org"
languageCode = "en-us"
theme = "ananke"
title = "Yen's blog"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 9 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

# Allow Goldmark to render raw HTML
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[languages]
  [languages.en]
    title = "Yen's blog"
    weight = 1
    contentDir = "content/en"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  description = "Lens, wheels, skates, keyboard"
  facebook = ""
  favicon = ""
  github = "https://github.com/dinhyen"
  gitlab = ""
  instagram = ""
  linkedin = "https://www.linkedin.com/in/dinhyen"
  mastodon = ""
  rss = ""
  site_logo = ""
  slack = ""
  stackoverflow = ""
  twitter = ""
  youtube = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 3